name: Run wdio:web

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Run wdio:web
      run: npm run wdio:web

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: .tmp/report
